### ISSUE TITLE
Level::fromName has been removed in Rollbar

### ISSUE THREAD

**Issue by matjack1** [baibaratsky/yii-rollbar#8]
Hello,

I've noticed that in the Rollbar library the Level::fromName method doesn't exist anymore, and this causes issues with your library.

I've asked them about their plans: https://github.com/rollbar/rollbar-php/issues/244, maybe you should revert my last PR meanwhile, as it's partially broken :)

**Comment by baibaratsky** [comment]
Please test your code before creating a pull request

**Comment by matjack1** [comment]
Sorry, you are right, I'll update this again soon.

**Comment by ArturMoczulski** [comment]
@matjack1 `Level::fromName` has been intentionally removed from `rollbar/rollbar-php`. `baibaratsky/yii-rollbar` needs to be updated. @matjack1 let me know if you need any help on the new pull request.
